### ISSUE TITLE
SpyderAPIError: register was replaced by on_initialize

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder5-plugin-cookiecutter#4]
When using the template I get the following error after installing the plugin:

```Python
Traceback (most recent call last):
  File "C:\Users\skjerns\Desktop\spyder\spyder\app\mainwindow.py", line 909, in setup
    plugin_instance = PLUGIN_REGISTRY.register_plugin(
  File "C:\Users\skjerns\Desktop\spyder\spyder\api\plugin_registration\registry.py", line 274, in register_plugin
    instance = self._instantiate_spyder5_plugin(
  File "C:\Users\skjerns\Desktop\spyder\spyder\api\plugin_registration\registry.py", line 161, in _instantiate_spyder5_plugin
    plugin_instance.initialize()
  File "C:\Users\skjerns\Desktop\spyder\spyder\api\plugins\new_api.py", line 603, in initialize
    self.on_initialize()
  File "C:\Users\skjerns\Desktop\spyder\spyder\api\plugins\new_api.py", line 697, in on_initialize
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information
```

I think that this is just a simple replace of the function call in the template, right?

**Comment by ccordoba12** [comment]
Thanks for reporting @skjerns! We hadn't had time to do that, but I'll do it now because we need this for other things too.
